"""AI and Machine Learning Domain Knowledge Generator.
Comprehensive, in-depth coverage across Machine Learning, Deep Learning, NLP, RAG, Information Retrieval, and Speech.
"""
from __future__ import annotations

def get_ai_ml_documents() -> list[dict]:
    data = [
        # --- 1. AI & MACHINE LEARNING FOUNDATIONS ---
        ("ai-fundamentals", "Artificial Intelligence (AI) Foundations and Paradigms", "ai_foundations",
         "Artificial Intelligence (AI) is the computational science of synthesizing intelligent agents capable of perceiving environments, reasoning, learning, and executing autonomous actions. AI encompasses Symbolic AI (knowledge graphs, expert systems, rule engines) and Connectionist AI (statistical machine learning, artificial neural networks, deep learning models)."),
        ("ai-machine-learning-types", "Machine Learning Paradigms: Supervised, Unsupervised, and RL", "machine_learning",
         "Machine Learning (ML) develops mathematical algorithms that iteratively learn statistical relationships from training data. Supervised Learning maps labeled inputs to outputs (classification, regression). Unsupervised Learning discovers latent structures in unlabeled data (clustering, dimensionality reduction, density estimation). Reinforcement Learning optimizes sequential decision-making policies through environment interaction and reward maximization."),
        ("ai-linear-regression", "Linear and Polynomial Regression", "machine_learning",
         "Linear Regression models the continuous relationship between dependent target variable y and independent features X using linear parameters beta: y = X*beta + epsilon. Parameters are solved analytically via Ordinary Least Squares (OLS: beta = (X^T * X)^(-1) * X^T * y) or numerically via Gradient Descent minimizing Mean Squared Error (MSE). Polynomial regression models non-linear relationships by introducing higher-order feature powers."),
        ("ai-regularization", "Regularization Techniques: Ridge (L2), Lasso (L1), and ElasticNet", "machine_learning",
         "Regularization mitigates overfitting by penalizing large model coefficients during loss minimization. Ridge Regression (L2 regularization) adds lambda * sum(beta_i^2) to the loss function, shrinking coefficients toward zero while retaining all features. Lasso Regression (L1 regularization) adds lambda * sum(|beta_i|), driving non-informative coefficients exactly to zero to perform automated feature selection. ElasticNet linearly combines L1 and L2 penalties."),
        ("ai-logistic-regression", "Logistic Regression and Binary Cross-Entropy Loss", "machine_learning",
         "Logistic Regression is a linear classification algorithm estimating the posterior probability P(Y=1|X) that an input belongs to a positive class. It applies the non-linear Sigmoid activation function sigma(z) = 1 / (1 + e^(-z)) to a linear combination of features z = w^T * x + b. Model parameters are optimized using Gradient Descent minimizing Binary Cross-Entropy (Log Loss)."),
        ("ai-decision-trees", "Decision Trees and Splitting Criteria (Gini and Entropy)", "machine_learning",
         "Decision Trees (e.g., CART, ID3, C4.5) are non-parametric supervised models that recursively partition feature space into orthogonal regions. Split selection chooses the feature and threshold that maximizes purity gain measured via Information Gain (Entropy reduction: H(S) = -sum(p_i * log2(p_i))) or Gini Impurity reduction (Gini = 1 - sum(p_i^2)). Tree pruning prevents deep trees from memorizing training noise."),
        ("ai-random-forests", "Random Forests and Bagging Ensembles", "machine_learning",
         "Random Forest is an ensemble learning method combining multiple de-correlated decision trees via Bootstrap Aggregating (Bagging). Each tree is trained on a bootstrap sample of the dataset, and each split evaluates only a random subset of m = sqrt(p) candidate features. Aggregating predictions via majority voting (classification) or averaging (regression) substantially reduces variance without increasing bias."),
        ("ai-gradient-boosting", "Gradient Boosted Decision Trees (GBDT, XGBoost, LightGBM)", "machine_learning",
         "Gradient Boosting constructs an ensemble sequentially by training each new weak decision tree to predict the negative gradient (pseudo-residuals) of the loss function with respect to current ensemble predictions. Modern implementations like XGBoost, LightGBM, and CatBoost incorporate second-order Taylor expansion approximations, L1/L2 tree complexity regularization, histogram-based split finding, and GPU acceleration."),
        ("ai-svm", "Support Vector Machines (SVM) and the Kernel Trick", "machine_learning",
         "Support Vector Machines (SVM) find the optimal separating hyperplane that maximizes the geometric margin between distinct classes. Data points lying on the margin boundary are called Support Vectors. For non-linearly separable data, the Kernel Trick maps inputs into high-dimensional feature spaces via kernel functions (Radial Basis Function RBF, Polynomial) without explicitly calculating high-dimensional coordinate vectors (Mercer's Theorem)."),
        ("ai-knn-naive-bayes", "K-Nearest Neighbors (KNN) and Naive Bayes Classifiers", "machine_learning",
         "K-Nearest Neighbors (KNN) is a lazy, instance-based non-parametric classifier that assigns labels by computing majority vote across the k closest training examples using Euclidean or Manhattan distance metrics. Naive Bayes is a probabilistic classifier applying Bayes' Theorem P(C|X) = (P(X|C) * P(C)) / P(X) with the 'naive' assumption of conditional feature independence given the class label."),
        ("ai-clustering-kmeans-dbscan", "Clustering Algorithms: K-Means, Hierarchical, and DBSCAN", "machine_learning",
         "K-Means partitions n observations into k clusters by alternating between assigning points to the nearest centroid and recalculating centroids via Lloyd's algorithm until convergence (evaluated using Silhouette Score and Elbow method). Hierarchical clustering builds nested dendrogram trees via agglomerative bottom-up merging. DBSCAN (Density-Based Spatial Clustering of Applications with Noise) groups points in dense regions based on radius epsilon and minimum points minPts, discovering arbitrary cluster shapes while labeling noise."),
        ("ai-dimensionality-reduction", "Dimensionality Reduction: PCA, SVD, and t-SNE", "machine_learning",
         "Principal Component Analysis (PCA) is an orthogonal linear transformation that projects high-dimensional data onto orthogonal axes (principal components) maximizing data variance via Singular Value Decomposition (SVD) of the centered covariance matrix. t-Distributed Stochastic Neighbor Embedding (t-SNE) is a non-linear manifold technique preserving local pairwise probabilities for 2D/3D visualization."),
        ("ai-model-evaluation-metrics", "Model Evaluation Metrics: Precision, Recall, F1, and ROC-AUC", "machine_learning",
         "In classification evaluation: Precision = TP / (TP + FP) measures exactness (fraction of positive predictions that are true). Recall (Sensitivity) = TP / (TP + FN) measures completeness (fraction of actual positives detected). F1 Score = 2 * (Precision * Recall) / (Precision + Recall) is the harmonic mean balancing precision and recall. The ROC Curve plots True Positive Rate vs False Positive Rate across all classification thresholds, summarized by the Area Under the Curve (ROC-AUC)."),
        ("ai-reinforcement-learning", "Reinforcement Learning: MDPs, Q-Learning, and Policy Gradients", "machine_learning",
         "Reinforcement Learning formalizes goal-directed learning as a Markov Decision Process (MDP) defined by states S, actions A, transition probabilities P, rewards R, and discount factor gamma. Value-based methods (Q-Learning, Deep Q-Networks DQN) estimate the optimal state-action value function Q*(s,a) using the Bellman Optimality Equation. Policy-based methods (REINFORCE, PPO) directly parameterize and optimize policy probability distributions pi_theta(a|s) using gradient ascent."),

        # --- 2. DEEP LEARNING & NEURAL NETWORKS ---
        ("ai-neural-networks-backprop", "Artificial Neural Networks, Forward Propagation, and Backpropagation", "deep_learning",
         "Artificial Neural Networks compose layers of artificial neurons. Forward propagation computes affine transformations z = W*x + b followed by non-linear activations a = f(z). Backpropagation computes the analytical gradient of the scalar loss function with respect to every weight tensor throughout the network by applying the chain rule of differential calculus from output back to input layers."),
        ("ai-activation-functions", "Activation Functions: ReLU, GELU, Sigmoid, and Softmax", "deep_learning",
         "Activation functions introduce non-linearity into neural networks, enabling universal function approximation. Rectified Linear Unit (ReLU: max(0, x)) avoids vanishing gradients for positive inputs. Gaussian Error Linear Unit (GELU: x * Phi(x)) weights inputs by their probability under a Gaussian distribution (standard in BERT/GPT). Sigmoid maps inputs to (0, 1) for probabilities. Softmax normalizes a vector of logits into a probability distribution summing to 1."),
        ("ai-optimization-adam-sgd", "Neural Network Optimization: SGD, Momentum, and Adam", "deep_learning",
         "Stochastic Gradient Descent (SGD) updates weights using mini-batch gradient estimates: w = w - lr * grad. Momentum accelerates SGD along consistent descent directions by accumulating an exponentially decaying moving average of past gradients. Adam (Adaptive Moment Estimation) computes individual adaptive learning rates for each parameter by tracking both first moments (mean gradient) and second uncentered moments (variance), providing fast convergence."),
        ("ai-cnn-architectures", "Convolutional Neural Networks (CNNs) and ResNet", "deep_learning",
         "CNNs process grid-structured data (images, audio spectrograms) using learnable convolutional kernels that extract translation-invariant spatial features, followed by pooling operations (Max Pooling) for spatial downsampling. Deep CNNs (such as ResNet) introduce Residual Skip Connections (identity shortcuts: y = F(x) + x) that allow gradients to flow directly through hundreds of layers without vanishing."),
        ("ai-rnn-lstm-gru", "Recurrent Neural Networks (RNNs), LSTMs, and GRUs", "deep_learning",
         "Recurrent Neural Networks (RNNs) process variable-length sequences by passing internal hidden state vectors h_t = tanh(W_h * h_(t-1) + W_x * x_t) across time steps. Long Short-Term Memory (LSTM) networks resolve the vanishing gradient problem using a dedicated constant-error carousel (cell state C_t) regulated by three multiplicative gates: Forget Gate f_t, Input Gate i_t, and Output Gate o_t. Gated Recurrent Units (GRUs) simplify this with Reset and Update gates."),

        # --- 3. TRANSFORMERS & NATURAL LANGUAGE PROCESSING (NLP) ---
        ("ai-transformers-attention", "The Transformer Architecture and Self-Attention", "transformers",
         "The Transformer architecture replaces recurrence entirely with multi-head self-attention mechanisms. Self-attention projects input token embeddings into Query (Q), Key (K), and Value (V) representations. The Scaled Dot-Product Attention computes attention weights dynamically across all token pairs in parallel: Attention(Q, K, V) = softmax( (Q * K^T) / sqrt(d_k) ) * V. Multi-Head Attention projects inputs into multiple distinct attention heads to capture diverse syntactic and semantic relationships."),
        ("ai-positional-encodings", "Positional Encodings: Sinusoidal, Learned, and RoPE", "transformers",
         "Because self-attention is permutation-invariant, Transformers require positional encodings to inject token sequence order. Sinusoidal Positional Encodings add fixed sinusoidal waves of varying frequencies. Learned Positional Embeddings train distinct position vectors. Rotary Position Embeddings (RoPE) encode relative token distance by rotating Query and Key vectors in 2D coordinate subspaces via rotation matrices, improving length generalization in modern LLMs like LLaMA."),
        ("ai-bert-gpt", "Encoder-Only vs Decoder-Only Transformers (BERT and GPT)", "transformers",
         "Transformer architectures diverge into three paradigms: Encoder-Only models (BERT, RoBERTa) use bidirectional self-attention trained via Masked Language Modeling (MLM), optimal for sentence embedding, classification, and extraction. Decoder-Only models (GPT-3, GPT-4, LLaMA, Mistral) use causal masked self-attention to prevent attending to future tokens, trained via autoregressive next-token prediction for generative text completion. Encoder-Decoder models (T5, Whisper) map input sequences to target sequences."),
        ("ai-nlp-tokenization", "NLP Tokenization Algorithms: BPE, WordPiece, and SentencePiece", "nlp",
         "Tokenization segments text into discrete subword units, balancing vocabulary size with sequence length while eliminating Out-Of-Vocabulary (OOV) errors. Byte-Pair Encoding (BPE) iteratively merges the most frequent pairs of characters or bytes in a training corpus. WordPiece merges pairs that maximize the likelihood of a language model. SentencePiece operates directly on raw Unicode byte streams without language-specific pre-tokenization."),
        ("ai-embeddings-vector-spaces", "Dense Vector Embeddings and Semantic Vector Spaces", "nlp",
         "Dense vector embeddings (e.g., Word2Vec, BERT, Multilingual E5) project discrete words, sentences, or documents into continuous vector spaces R^d where semantic relatedness corresponds to geometric proximity. Cosine similarity cos(theta) = (u . v) / (||u|| * ||v||) measures angular alignment between normalized vectors, capturing synonyms, paraphrases, and cross-lingual equivalence."),

        # --- 4. INFORMATION RETRIEVAL & VECTOR SEARCH ---
        ("ai-vector-search-ann", "Vector Search and Approximate Nearest Neighbor (ANN) Algorithms", "information_retrieval",
         "Vector search retrieves the most similar vectors to a query embedding from billion-scale databases. Exact Flat search (IndexFlatIP, IndexFlatL2) computes brute-force distance to every vector in O(N*d) time. Approximate Nearest Neighbor (ANN) trade minor recall for orders-of-magnitude speedup: Inverted File (IVFFlat) partitions space into Voronoi cells via k-means clustering; Hierarchical Navigable Small World (HNSW) constructs multi-layer proximity graphs with logarithmic search complexity."),
        ("ai-faiss", "FAISS Library Architecture and Index Types", "information_retrieval",
         "FAISS (Facebook AI Similarity Search) is an open-source C++ library with Python bindings developed by Meta AI for dense vector similarity search and clustering. FAISS supports GPU-accelerated and CPU search across index types: IndexFlatIP (exact cosine similarity over normalized vectors), IndexIVFFlat (inverted file clustering for fast coarse search), IndexHNSWFlat (graph-based ANN), and Product Quantization (PQ for massive vector memory compression)."),
        ("ai-bm25-lexical", "BM25 (Best Matching 25) Probabilistic Lexical Retrieval", "information_retrieval",
         "BM25 is a probabilistic lexical ranking function used in search engines to rank documents based on query search terms. Extending classical TF-IDF, BM25 computes relevance score S(D, Q) = sum( IDF(q_i) * (f(q_i, D) * (k1 + 1)) / (f(q_i, D) + k1 * (1 - b + b * (|D| / avgdl))) ). Parameter k1 controls term frequency saturation; parameter b controls document length normalization penalty."),
        ("ai-hybrid-rrf", "Hybrid Search and Reciprocal Rank Fusion (RRF)", "information_retrieval",
         "Hybrid search merges dense semantic retrieval (FAISS) and sparse lexical retrieval (BM25) to capture both high-level conceptual intent and exact technical keyword matches. Reciprocal Rank Fusion (RRF) scores each document d across m retriever rankings using RRF_Score(d) = sum_{i=1}^m 1 / (k + rank_i(d)), where k=60 is a smoothing constant. RRF eliminates score scale incompatibility without requiring machine-learned calibration weights."),
        ("ai-cross-encoder-reranking", "Two-Stage Search and Cross-Encoder Reranking", "information_retrieval",
         "Two-stage information retrieval balances search latency and ranking precision. First-stage retrieval retrieves top candidate documents (e.g., top 100) using fast bi-encoder vector embeddings or BM25 in milliseconds. Second-stage rerankers pass the query and candidate documents jointly through a Cross-Encoder Transformer, computing deep token-level cross-attention interactions for maximum ranking accuracy."),

        # --- 5. RETRIEVAL-AUGMENTED GENERATION (RAG) & SPEECH AI ---
        ("ai-rag-architecture", "Retrieval-Augmented Generation (RAG) Pipeline Architecture", "rag",
         "Retrieval-Augmented Generation (RAG) grounds Large Language Model (LLM) responses in external authoritative knowledge bases. When a user submits a query, the RAG system retrieves relevant chunks from vector and lexical indexes, injects retrieved text as context into the LLM prompt, and instructs the LLM to generate an answer derived exclusively from that evidence with citations, mitigating hallucinations and enabling real-time knowledge updates."),
        ("ai-rag-chunking", "Document Chunking Strategies in RAG: Fixed, Sentence, and Hierarchical", "rag",
         "Document chunking partitions large source texts into digestible semantic units for vector embedding. Fixed-word chunking divides text into uniform token windows (e.g., 384 words) with sliding overlap (e.g., 64 words) to prevent context clipping. Sentence chunking respects sentence grammatical boundaries. Hierarchical chunking embeds granular sentence-level child chunks for precise retrieval while linking them to broader passage-level parent chunks for expanded LLM context generation."),
        ("ai-rag-grounding-refusal", "Evidence Grounding, Citation Validation, and Refusal Guardrails", "rag",
         "Zero-Hallucination RAG systems enforce strict grounding guardrails. The system evaluates retrieval relevance against minimum similarity thresholds. If retrieved evidence is weak or irrelevant, the system triggers a deterministic refusal ('I don\\'t have enough information to answer reliably'). During generation, the backend verifies that cited chunk IDs exist within the retrieved evidence set, rejecting any unverified or fabricated citation."),
        ("ai-speech-whisper-stt", "Automatic Speech Recognition (ASR) with OpenAI Whisper", "speech",
         "OpenAI Whisper is an encoder-decoder sequence-to-sequence Transformer trained on 680,000 hours of multilingual acoustic audio data. Audio waveforms are resampled to 16kHz, converted into 80-channel log-Mel spectrograms, and processed through an audio convolutional encoder. The autoregressive text decoder predicts sequence tokens using beam search, supporting speech transcription, voice activity detection, and language identification."),
        ("ai-speech-tts-neural", "Neural Text-to-Speech (TTS) and EdgeTTS", "speech",
         "Modern Neural Text-to-Speech (TTS) synthesizes human-like speech from written text. Text is parsed into phonetic and linguistic features, acoustic models predict intermediate representations (Mel-spectrograms or prosody pitch contours), and neural vocoders (e.g., HiFi-GAN, WaveNet) synthesize high-fidelity acoustic audio waveforms. Microsoft EdgeTTS provides low-latency neural speech streaming across diverse global languages and accents.")
    ]
    docs = []
    for doc_id, title, topic, text in data:
        docs.append({
            "document_id": doc_id,
            "passage_id": f"{doc_id}-1",
            "title": title,
            "domain": "ai_ml",
            "topic": topic,
            "language": "en",
            "source_type": "curated",
            "keywords": [k.lower() for k in title.split()],
            "text": text
        })
    return docs
