"""General Science Domain Knowledge Generator.
Comprehensive educational coverage of Physics, Chemistry, Biology, Earth Science, and Astronomy.
"""
from __future__ import annotations

def get_general_science_documents() -> list[dict]:
    data = [
        # --- 1. PHYSICS ---
        ("sci-phys-newton-laws", "Newton's Laws of Classical Motion", "physics",
         "Sir Isaac Newton formulated the three fundamental laws of classical mechanics in the Principia Mathematica: First Law (Law of Inertia) states that an object remains at rest or in uniform motion along a straight line unless acted upon by a net external force. Second Law states that force equals mass times acceleration: F = m*a (or F = dp/dt). Third Law dictates that for every applied action force, there is an equal and opposite reaction force."),
        ("sci-phys-work-energy-momentum", "Work, Energy, and Conservation Laws in Physics", "physics",
         "In physics, Work is done when a force acts on an object over a displacement: W = F . d = F * d * cos(theta). Kinetic Energy is the energy of motion: KE = 0.5 * m * v^2. Gravitational Potential Energy is stored energy: PE = m * g * h. The Law of Conservation of Energy dictates that total energy in an isolated system remains constant, transforming between kinetic, potential, and thermal forms. Linear Momentum p = m*v is conserved in the absence of external net impulses."),
        ("sci-phys-gravity", "Gravity and Universal Gravitation", "physics",
         "Gravity is the fundamental natural force of attraction between all objects possessing mass or energy. Newton's Law of Universal Gravitation states that the gravitational force between two point masses m1 and m2 separated by distance r is given by F = G * (m1 * m2) / r^2, where G is the gravitational constant (6.674e-11 N m^2/kg^2). Albert Einstein's General Theory of Relativity describes gravity geometrically as the curvature of 4D spacetime caused by mass-energy distributions."),
        ("sci-phys-thermodynamics", "The Four Laws of Thermodynamics and Entropy", "physics",
         "Thermodynamics governs heat, work, and energy conversion across physical systems. The Zeroth Law defines thermal equilibrium and temperature. The First Law (Conservation of Energy) states delta U = Q - W, where change in internal energy equals heat added minus work done. The Second Law dictates that the total entropy (measure of molecular disorder) of an isolated system always increases over time (delta S >= 0). The Third Law states that entropy approaches a constant minimum as temperature approaches absolute zero (0 Kelvin)."),
        ("sci-phys-electromagnetism", "Electromagnetism and Maxwell's Equations", "physics",
         "Electromagnetism governs electric charges and magnetic fields, unified by James Clerk Maxwell into four fundamental equations: Gauss's Law for electricity (electric flux relates to enclosed charge), Gauss's Law for magnetism (magnetic monopoles do not exist), Faraday's Law of Induction (time-varying magnetic fields induce electric fields: emf = -dPhi/dt), and the Ampere-Maxwell Law (electric currents and time-varying electric fields generate magnetic fields), proving light is an electromagnetic wave propagating at speed c."),
        ("sci-phys-waves-optics", "Wave Mechanics, Snell's Law, and Optics", "physics",
         "Waves transfer energy through oscillations without net mass transport, characterized by wavelength lambda, frequency f, amplitude A, and wave speed v = f * lambda. Light exhibits wave-particle duality. Reflection follows angle_i = angle_r. Refraction (bending of light across media with refractive indices n1, n2) obeys Snell's Law: n1 * sin(theta_1) = n2 * sin(theta_2). Wave phenomena include diffraction (bending around obstacles), interference (constructive and destructive superposition), and polarization."),
        ("sci-phys-relativity-quantum", "Special Relativity and Quantum Mechanics Fundamentals", "physics",
         "Albert Einstein's Special Relativity rests on two postulates: laws of physics are invariant across all inertial frames, and the speed of light in vacuum c is constant for all observers regardless of relative motion, deriving time dilation, length contraction, and mass-energy equivalence E = m * c^2. Quantum mechanics describes physical phenomena at atomic scales where energy is quantized (E = h * f, Planck's constant), particles exhibit wave-particle duality (de Broglie wavelength), and Heisenberg's Uncertainty Principle prohibits simultaneously measuring position and momentum with arbitrary precision: delta x * delta p >= hbar / 2."),

        # --- 2. CHEMISTRY ---
        ("sci-chem-atomic-structure", "Atomic Structure, Subatomic Particles, and Orbitals", "chemistry",
         "Atoms are the foundational building blocks of chemical matter, consisting of a dense central nucleus composed of positively charged protons and neutral neutrons, surrounded by negatively charged electrons occupying quantized energy orbitals. The atomic number Z equals the number of protons and defines the element; mass number A equals protons plus neutrons. Electron configurations follow the Aufbau Principle (filling lowest energy orbitals first), Pauli Exclusion Principle (no two electrons share identical quantum numbers), and Hund's Rule."),
        ("sci-chem-periodic-table", "The Periodic Table of Elements and Periodic Trends", "chemistry",
         "The Periodic Table organizes all 118 known chemical elements by increasing atomic number Z into 18 vertical groups and 7 horizontal periods. Elements in identical groups share valence electron configurations and chemical properties. Key periodic trends include: Atomic Radius decreases across a period and increases down a group; Ionization Energy (energy required to remove an electron) increases across a period and decreases down a group; Electronegativity (tendency of an atom to attract shared electrons in a bond) increases toward Fluorine (top right)."),
        ("sci-chem-chemical-bonding", "Chemical Bonding: Ionic, Covalent, and Metallic", "chemistry",
         "Chemical bonds form to minimize potential energy and achieve stable valence octets. Covalent Bonds form when nonmetal atoms share pairs of valence electrons (single, double, or triple bonds; polar if electronegativity difference exists). Ionic Bonds form via electrostatic attraction between oppositely charged cations and anions resulting from electron transfer from metals to nonmetals. Metallic Bonds involve metal cations immersed in a delocalized 'sea' of mobile valence electrons, imparting high electrical and thermal conductivity."),
        ("sci-chem-reactions-stoichiometry", "Chemical Reactions, Balancing, and Stoichiometry", "chemistry",
         "Chemical reactions transform reactants into products by breaking and forming chemical bonds while strictly conserving mass, charge, and atoms. Stoichiometry uses mole ratios from balanced chemical equations to calculate theoretical yields and determine limiting reagents. A mole represents Avogadro's number of particles (N_A = 6.022e23 particles/mol). Reaction categories include synthesis, decomposition, single displacement, double displacement, and combustion."),
        ("sci-chem-acids-bases-ph", "Acids, Bases, the pH Scale, and Neutralization", "chemistry",
         "According to the Bronsted-Lowry definition, an acid is a proton (H+) donor, and a base is a proton acceptor. In aqueous solutions, the pH scale quantifies hydrogen ion concentration: pH = -log10[H3O+]. Neutral water at 25 degrees Celsius has a pH of 7; acidic solutions have pH < 7 ([H3O+] > 1e-7 M); basic (alkaline) solutions have pH > 7 ([OH-] > 1e-7 M). Neutralization occurs when an acid reacts with a base to produce water and an ionic salt (e.g., HCl + NaOH -> NaCl + H2O)."),

        # --- 3. BIOLOGY ---
        ("sci-bio-cell-structure", "Cell Biology, Organelles, and Membrane Transport", "biology",
         "The cell is the structural and functional unit of all living organisms. Prokaryotic cells (bacteria, archaea) lack membrane-bound organelles and a true nucleus. Eukaryotic cells (plant, animal, fungi) contain specialized organelles: the Nucleus (houses chromosomal DNA), Mitochondria (generates ATP via cellular respiration), Ribosomes (protein synthesis), Endoplasmic Reticulum (lipid synthesis and protein processing), Golgi Apparatus (modifies and packages proteins), and Chloroplasts (photosynthesis in plants). The semipermeable phospholipid bilayer plasma membrane regulates transport via diffusion, osmosis, facilitated diffusion, and ATP-powered active transport."),
        ("sci-bio-dna-genetics", "DNA Structure, RNA, and the Central Dogma of Molecular Biology", "biology",
         "Deoxyribonucleic Acid (DNA) is a double-stranded antiparallel helix composed of nucleotide subunits (deoxyribose sugar, phosphate group, and nitrogenous bases: Adenine, Thymine, Guanine, Cytosine with complementary Watson-Crick base pairing A-T and G-C). The Central Dogma of Molecular Biology describes the unidirectional flow of genetic information: DNA replicates itself, undergoes Transcription by RNA Polymerase into single-stranded Messenger RNA (mRNA), and mRNA undergoes Translation at ribosomes where Transfer RNA (tRNA) assembles amino acids into polypeptide protein chains."),
        ("science-photosynthesis-en", "Photosynthesis in Green Plants and Algae", "biology",
         "Photosynthesis is the biological process by which green plants, algae, and cyanobacteria convert light energy into chemical energy. Using sunlight, water (H2O), and carbon dioxide (CO2), chloroplasts containing chlorophyll produce glucose (C6H12O6) and release oxygen gas (O2) into the atmosphere as a vital by-product: 6CO2 + 6H2O + Light -> C6H12O6 + 6O2. The process comprises the Light-Dependent Reactions (producing ATP and NADPH in thylakoid membranes) and the Light-Independent Calvin Cycle (fixing CO2 into sugars in the stroma)."),
        ("sci-bio-cellular-respiration", "Cellular Respiration and ATP Generation", "biology",
         "Cellular respiration is the biochemical catabolic pathway by which eukaryotic cells oxidize glucose in the presence of oxygen to produce adenosine triphosphate (ATP), the primary energy currency of biological cells: C6H12O6 + 6O2 -> 6CO2 + 6H2O + ~36-38 ATP. The pathway consists of three sequential stages: Glycolysis in the cytosol (anaerobic glucose breakdown to pyruvate), the Citric Acid (Krebs) Cycle in the mitochondrial matrix (producing NADH and FADH2), and Oxidative Phosphorylation via the Electron Transport Chain and ATP Synthase on the inner mitochondrial membrane."),
        ("sci-bio-evolution-genetics", "Biological Evolution, Natural Selection, and Mendelian Genetics", "biology",
         "Biological evolution is the change in heritable traits of biological populations over successive generations. Charles Darwin and Alfred Russel Wallace identified Natural Selection as the primary evolutionary mechanism: organisms with advantageous phenotypic adaptations suited to environmental selective pressures exhibit differential reproductive success, passing alleles to offspring. Gregor Mendel established the laws of inheritance: Law of Segregation (alleles separate during gamete formation) and Law of Independent Assortment."),
        ("sci-bio-human-physiology", "Human Physiology: Circulatory, Nervous, and Immune Systems", "biology",
         "Human physiology encompasses organ systems maintaining homeostasis. The Circulatory System (heart, arteries, veins, capillaries) pumps oxygenated blood and nutrients throughout the body. The Nervous System (brain, spinal cord, peripheral nerves) transmits electrochemical action potentials via neurons across synaptic junctions for rapid signaling. The Immune System (white blood cells, antibodies, lymphoid organs) defends against pathogens through innate non-specific barriers and adaptive antigen-specific humoral and cell-mediated immunity."),

        # --- 4. EARTH SCIENCE & ASTRONOMY ---
        ("sci-earth-atmosphere-climate", "Earth's Atmosphere, Layers, and Weather Systems", "earth_science",
         "Earth's atmosphere is a protective gaseous envelope composed of nitrogen (78.08%), oxygen (20.95%), argon (0.93%), carbon dioxide (0.04%), and variable water vapor. It is divided into five thermal layers: Troposphere (0-12 km, where weather occurs and temperature decreases with altitude), Stratosphere (12-50 km, containing the ozone layer absorbing UV radiation), Mesosphere (50-85 km, where meteors burn), Thermosphere (85-600 km, containing the ionosphere), and Exosphere (transitioning into outer space)."),
        ("sci-earth-water-cycle", "The Hydrologic (Water) Cycle and Ocean Currents", "earth_science",
         "The hydrologic (water) cycle describes the continuous solar-driven global circulation of water. Water evaporates from oceans and surface bodies, transpires from terrestrial vegetation, ascends and condenses into clouds in the troposphere, and precipitates back to Earth as rain, snow, or hail, replenishing groundwater aquifers, rivers, and oceans via surface runoff. Global thermohaline ocean currents distribute heat and regulate worldwide climate."),
        ("sci-earth-plate-tectonics", "Plate Tectonics, Earthquakes, and Geology", "earth_science",
         "Plate tectonics describes the motion of Earth's rigid lithospheric plates floating over the ductile asthenosphere driven by mantle convection currents. Plate boundaries include Convergent Boundaries (subduction zones forming deep ocean trenches and volcanic mountain arcs), Divergent Boundaries (seafloor spreading at mid-ocean ridges), and Transform Boundaries (horizontal strike-slip faulting causing seismic earthquakes, e.g., San Andreas Fault). The Rock Cycle continuously transforms igneous, sedimentary, and metamorphic rocks."),
        ("sci-astro-solar-system", "The Solar System, Planetary Bodies, and Kepler's Laws", "astronomy",
         "The Solar System consists of the Sun (a G-type main-sequence star containing 99.86% of total system mass) and gravitationally bound bodies orbiting it. The eight recognized planets in order of distance from the Sun are: terrestrial rocky planets (Mercury, Venus, Earth, Mars) and Jovian outer giants (gas giants Jupiter and Saturn; ice giants Uranus and Neptune). Johannes Kepler formulated three laws of planetary motion: planets orbit the Sun in ellipses with the Sun at one focus; orbital radius sweeps out equal areas in equal times; the square of orbital period T^2 is proportional to the cube of semi-major axis a^3."),
        ("sci-astro-stellar-evolution-black-holes", "Stellar Evolution, Supernovas, and Black Holes", "astronomy",
         "Stars form in giant molecular clouds through gravitational collapse and generate outward thermal radiation pressure via core nuclear fusion of hydrogen into helium (main sequence). When high-mass stars exhaust nuclear fuel, core collapse triggers a violent Type II Supernova explosion, leaving behind extremely dense stellar remnants: Neutron Stars (pulsars supported by neutron degeneracy pressure) or Black Holes (gravitational singularities surrounded by an event horizon from which nothing, not even light, can escape).")
    ]
    docs = []
    for doc_id, title, topic, text in data:
        docs.append({
            "document_id": doc_id,
            "passage_id": f"{doc_id}-1",
            "title": title,
            "domain": "general_science",
            "topic": topic,
            "language": "en",
            "source_type": "curated",
            "keywords": [k.lower() for k in title.split()],
            "text": text
        })
    return docs
